#!/bin/sh
# doc-status-check.sh — PUB1b doc status gate
# (ompkit-rc-epic-land-fix-release-dogfood-rz5.106.2).
# Every doc carries YAML front matter with a status (current, draft or
# superseded); a superseded doc names its replacement in superseded-by, and a
# dangling target is refused. With --index the script regenerates docs/INDEX.md
# (current, draft and superseded groups); the output is sorted, so a second
# run produces no diff.
# Usage: doc-status-check.sh [REPO] [--index]
# Exit 0 clean, 1 on a status violation, 2 on usage errors.
set -u

fail() {
	printf 'doc-status: %s\n' "$1" >&2
	exit 2
}

REPO=.
INDEX=0
for arg in "$@"; do
	case "$arg" in
		--index) INDEX=1 ;;
		-*) fail "usage: doc-status-check.sh [REPO] [--index]" ;;
		*) REPO=$arg ;;
	esac
done
[ -d "$REPO" ] || fail "not a directory: $REPO"

LIST=$(mktemp) || fail "cannot create work file"
trap 'rm -f "$LIST"' EXIT INT TERM
if [ -d "$REPO/docs" ]; then
	find "$REPO/docs" -maxdepth 1 -name '*.md' ! -name 'INDEX.md' | sort >> "$LIST"
fi
for root in README.md ROADMAP.md AGENTS.md CONTRIBUTING.md; do
	[ -f "$REPO/$root" ] || continue
	printf '%s\n' "$REPO/$root" >> "$LIST"
done
[ -s "$LIST" ] || fail "no docs found under $REPO"

bad=0
current_list=$(mktemp) || fail "cannot create work file"
draft_list=$(mktemp) || fail "cannot create work file"
superseded_list=$(mktemp) || fail "cannot create work file"
trap 'rm -f "$LIST" "$current_list" "$draft_list" "$superseded_list"' EXIT INT TERM

while IFS= read -r file; do
	rel=${file#"$REPO"/}
	first=$(sed -n '1p' "$file")
	if [ "$first" != "---" ]; then
		printf 'doc-status: %s has no front matter status\n' "$rel" >&2
		bad=1
		continue
	fi
	block=$(awk 'NR==1 && $0=="---" {next} $0=="---" {exit} {print}' "$file")
	status=$(printf '%s\n' "$block" | sed -n 's/^status:[[:space:]]*//p' | head -n 1)
	target=$(printf '%s\n' "$block" | sed -n 's/^superseded-by:[[:space:]]*//p' | head -n 1)
	case "$status" in
		current) printf '%s\n' "$rel" >> "$current_list" ;;
		draft) printf '%s\n' "$rel" >> "$draft_list" ;;
		superseded)
			if [ -z "$target" ]; then
				printf 'doc-status: %s is superseded without a superseded-by target\n' "$rel" >&2
				bad=1
				continue
			fi
			if [ ! -f "$REPO/$target" ]; then
				printf 'doc-status: %s superseded-by points nowhere: %s\n' "$rel" "$target" >&2
				bad=1
				continue
			fi
			printf '%s -> %s\n' "$rel" "$target" >> "$superseded_list"
			;;
		*) printf 'doc-status: %s has unknown status %s\n' "$rel" "${status:-<empty>}" >&2
			bad=1
			continue
			;;
	esac
done < "$LIST"

if [ "$INDEX" -eq 1 ]; then
	{
		printf '# Docs index\n\nGenerated by sh scripts/doc-status-check.sh --index; do not edit by hand.\n\n'
		printf '## Current\n\n'
		sort "$current_list" | sed 's/^/- /'
		printf '\n## Draft\n\n'
		sort "$draft_list" | sed 's/^/- /'
		printf '\n## Superseded\n\n'
		sort "$superseded_list" | sed 's/^/- /'
	} > "$REPO/docs/INDEX.md"
fi

if [ "$bad" -ne 0 ]; then
	exit 1
fi
printf 'doc-status: %s clean\n' "$REPO" >&2
exit 0
